language: python
cache:
    directories:
        - $HOME/.cache/pip
install:
    - pip install  -r requirements/local.txt
    - pip install  -r requirements/test.txt
    - pip install coveralls
script:
    - cd acornaccounting && py.test && cd ..
after_success:
    - mv -f acornaccounting/.coverage . && coveralls
